//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiFiAAA.Open {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResultInfo", Namespace="http://aaa.nsu.edu.cn/")]
    [System.SerializableAttribute()]
    public partial class LoginResultInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NetGroupNameField;
        
        private System.DateTime ExpireTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private bool IsLoginField;
        
        private bool IsExpireField;
        
        private bool IsIDPWWrongField;
        
        private bool IsNeedUpdateField;
        
        private bool IsIPInvalidField;
        
        private bool IsDisableField;
        
        private bool IsWrongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NetGroupName {
            get {
                return this.NetGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NetGroupNameField, value) != true)) {
                    this.NetGroupNameField = value;
                    this.RaisePropertyChanged("NetGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime ExpireTime {
            get {
                return this.ExpireTimeField;
            }
            set {
                if ((this.ExpireTimeField.Equals(value) != true)) {
                    this.ExpireTimeField = value;
                    this.RaisePropertyChanged("ExpireTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsLogin {
            get {
                return this.IsLoginField;
            }
            set {
                if ((this.IsLoginField.Equals(value) != true)) {
                    this.IsLoginField = value;
                    this.RaisePropertyChanged("IsLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsExpire {
            get {
                return this.IsExpireField;
            }
            set {
                if ((this.IsExpireField.Equals(value) != true)) {
                    this.IsExpireField = value;
                    this.RaisePropertyChanged("IsExpire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsIDPWWrong {
            get {
                return this.IsIDPWWrongField;
            }
            set {
                if ((this.IsIDPWWrongField.Equals(value) != true)) {
                    this.IsIDPWWrongField = value;
                    this.RaisePropertyChanged("IsIDPWWrong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool IsNeedUpdate {
            get {
                return this.IsNeedUpdateField;
            }
            set {
                if ((this.IsNeedUpdateField.Equals(value) != true)) {
                    this.IsNeedUpdateField = value;
                    this.RaisePropertyChanged("IsNeedUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsIPInvalid {
            get {
                return this.IsIPInvalidField;
            }
            set {
                if ((this.IsIPInvalidField.Equals(value) != true)) {
                    this.IsIPInvalidField = value;
                    this.RaisePropertyChanged("IsIPInvalid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool IsDisable {
            get {
                return this.IsDisableField;
            }
            set {
                if ((this.IsDisableField.Equals(value) != true)) {
                    this.IsDisableField = value;
                    this.RaisePropertyChanged("IsDisable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool IsWrong {
            get {
                return this.IsWrongField;
            }
            set {
                if ((this.IsWrongField.Equals(value) != true)) {
                    this.IsWrongField = value;
                    this.RaisePropertyChanged("IsWrong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aaa.nsu.edu.cn/", ConfigurationName="Open.OpenAAASoap")]
    public interface OpenAAASoap {
        
        // CODEGEN: 命名空间 http://aaa.nsu.edu.cn/ 的元素名称 UserID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/Login", ReplyAction="*")]
        WiFiAAA.Open.LoginResponse Login(WiFiAAA.Open.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WiFiAAA.Open.LoginResponse> LoginAsync(WiFiAAA.Open.LoginRequest request);
        
        // CODEGEN: 命名空间 http://aaa.nsu.edu.cn/ 的元素名称 UserID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/LoginJson", ReplyAction="*")]
        WiFiAAA.Open.LoginJsonResponse LoginJson(WiFiAAA.Open.LoginJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/LoginJson", ReplyAction="*")]
        System.Threading.Tasks.Task<WiFiAAA.Open.LoginJsonResponse> LoginJsonAsync(WiFiAAA.Open.LoginJsonRequest request);
        
        // CODEGEN: 命名空间 http://aaa.nsu.edu.cn/ 的元素名称 UserID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/KeepSession", ReplyAction="*")]
        WiFiAAA.Open.KeepSessionResponse KeepSession(WiFiAAA.Open.KeepSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/KeepSession", ReplyAction="*")]
        System.Threading.Tasks.Task<WiFiAAA.Open.KeepSessionResponse> KeepSessionAsync(WiFiAAA.Open.KeepSessionRequest request);
        
        // CODEGEN: 命名空间 http://aaa.nsu.edu.cn/ 的元素名称 UserID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/Logout", ReplyAction="*")]
        WiFiAAA.Open.LogoutResponse Logout(WiFiAAA.Open.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<WiFiAAA.Open.LogoutResponse> LogoutAsync(WiFiAAA.Open.LogoutRequest request);
        
        // CODEGEN: 命名空间 http://aaa.nsu.edu.cn/ 的元素名称 GetTokenPictureBytesResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/GetTokenPictureBytes", ReplyAction="*")]
        WiFiAAA.Open.GetTokenPictureBytesResponse GetTokenPictureBytes(WiFiAAA.Open.GetTokenPictureBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aaa.nsu.edu.cn/GetTokenPictureBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<WiFiAAA.Open.GetTokenPictureBytesResponse> GetTokenPictureBytesAsync(WiFiAAA.Open.GetTokenPictureBytesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WiFiAAA.Open.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aaa.nsu.edu.cn/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserPW;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OpenAPIVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Token;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string UserID, string UserPW, string UserIP, string OpenAPIVersion, string Token) {
            this.UserID = UserID;
            this.UserPW = UserPW;
            this.UserIP = UserIP;
            this.OpenAPIVersion = OpenAPIVersion;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WiFiAAA.Open.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aaa.nsu.edu.cn/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WiFiAAA.Open.LoginResultInfo LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(WiFiAAA.Open.LoginResultInfo LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginJson", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.LoginJsonRequestBody Body;
        
        public LoginJsonRequest() {
        }
        
        public LoginJsonRequest(WiFiAAA.Open.LoginJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aaa.nsu.edu.cn/")]
    public partial class LoginJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserPW;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OpenAPIVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Token;
        
        public LoginJsonRequestBody() {
        }
        
        public LoginJsonRequestBody(string UserID, string UserPW, string UserIP, string OpenAPIVersion, string Token) {
            this.UserID = UserID;
            this.UserPW = UserPW;
            this.UserIP = UserIP;
            this.OpenAPIVersion = OpenAPIVersion;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginJsonResponse", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.LoginJsonResponseBody Body;
        
        public LoginJsonResponse() {
        }
        
        public LoginJsonResponse(WiFiAAA.Open.LoginJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aaa.nsu.edu.cn/")]
    public partial class LoginJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginJsonResult;
        
        public LoginJsonResponseBody() {
        }
        
        public LoginJsonResponseBody(string LoginJsonResult) {
            this.LoginJsonResult = LoginJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeepSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeepSession", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.KeepSessionRequestBody Body;
        
        public KeepSessionRequest() {
        }
        
        public KeepSessionRequest(WiFiAAA.Open.KeepSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aaa.nsu.edu.cn/")]
    public partial class KeepSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Token;
        
        public KeepSessionRequestBody() {
        }
        
        public KeepSessionRequestBody(string UserID, string Token) {
            this.UserID = UserID;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeepSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeepSessionResponse", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.KeepSessionResponseBody Body;
        
        public KeepSessionResponse() {
        }
        
        public KeepSessionResponse(WiFiAAA.Open.KeepSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aaa.nsu.edu.cn/")]
    public partial class KeepSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KeepSessionResult;
        
        public KeepSessionResponseBody() {
        }
        
        public KeepSessionResponseBody(string KeepSessionResult) {
            this.KeepSessionResult = KeepSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(WiFiAAA.Open.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aaa.nsu.edu.cn/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Token;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string UserID, string Token) {
            this.UserID = UserID;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(WiFiAAA.Open.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aaa.nsu.edu.cn/")]
    public partial class LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogoutResult;
        
        public LogoutResponseBody() {
        }
        
        public LogoutResponseBody(string LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenPictureBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenPictureBytes", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.GetTokenPictureBytesRequestBody Body;
        
        public GetTokenPictureBytesRequest() {
        }
        
        public GetTokenPictureBytesRequest(WiFiAAA.Open.GetTokenPictureBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTokenPictureBytesRequestBody {
        
        public GetTokenPictureBytesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenPictureBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenPictureBytesResponse", Namespace="http://aaa.nsu.edu.cn/", Order=0)]
        public WiFiAAA.Open.GetTokenPictureBytesResponseBody Body;
        
        public GetTokenPictureBytesResponse() {
        }
        
        public GetTokenPictureBytesResponse(WiFiAAA.Open.GetTokenPictureBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aaa.nsu.edu.cn/")]
    public partial class GetTokenPictureBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetTokenPictureBytesResult;
        
        public GetTokenPictureBytesResponseBody() {
        }
        
        public GetTokenPictureBytesResponseBody(byte[] GetTokenPictureBytesResult) {
            this.GetTokenPictureBytesResult = GetTokenPictureBytesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OpenAAASoapChannel : WiFiAAA.Open.OpenAAASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpenAAASoapClient : System.ServiceModel.ClientBase<WiFiAAA.Open.OpenAAASoap>, WiFiAAA.Open.OpenAAASoap {
        
        public OpenAAASoapClient() {
        }
        
        public OpenAAASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpenAAASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenAAASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenAAASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WiFiAAA.Open.LoginResponse WiFiAAA.Open.OpenAAASoap.Login(WiFiAAA.Open.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public WiFiAAA.Open.LoginResultInfo Login(string UserID, string UserPW, string UserIP, string OpenAPIVersion, string Token) {
            WiFiAAA.Open.LoginRequest inValue = new WiFiAAA.Open.LoginRequest();
            inValue.Body = new WiFiAAA.Open.LoginRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.UserPW = UserPW;
            inValue.Body.UserIP = UserIP;
            inValue.Body.OpenAPIVersion = OpenAPIVersion;
            inValue.Body.Token = Token;
            WiFiAAA.Open.LoginResponse retVal = ((WiFiAAA.Open.OpenAAASoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WiFiAAA.Open.LoginResponse> WiFiAAA.Open.OpenAAASoap.LoginAsync(WiFiAAA.Open.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WiFiAAA.Open.LoginResponse> LoginAsync(string UserID, string UserPW, string UserIP, string OpenAPIVersion, string Token) {
            WiFiAAA.Open.LoginRequest inValue = new WiFiAAA.Open.LoginRequest();
            inValue.Body = new WiFiAAA.Open.LoginRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.UserPW = UserPW;
            inValue.Body.UserIP = UserIP;
            inValue.Body.OpenAPIVersion = OpenAPIVersion;
            inValue.Body.Token = Token;
            return ((WiFiAAA.Open.OpenAAASoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WiFiAAA.Open.LoginJsonResponse WiFiAAA.Open.OpenAAASoap.LoginJson(WiFiAAA.Open.LoginJsonRequest request) {
            return base.Channel.LoginJson(request);
        }
        
        public string LoginJson(string UserID, string UserPW, string UserIP, string OpenAPIVersion, string Token) {
            WiFiAAA.Open.LoginJsonRequest inValue = new WiFiAAA.Open.LoginJsonRequest();
            inValue.Body = new WiFiAAA.Open.LoginJsonRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.UserPW = UserPW;
            inValue.Body.UserIP = UserIP;
            inValue.Body.OpenAPIVersion = OpenAPIVersion;
            inValue.Body.Token = Token;
            WiFiAAA.Open.LoginJsonResponse retVal = ((WiFiAAA.Open.OpenAAASoap)(this)).LoginJson(inValue);
            return retVal.Body.LoginJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WiFiAAA.Open.LoginJsonResponse> WiFiAAA.Open.OpenAAASoap.LoginJsonAsync(WiFiAAA.Open.LoginJsonRequest request) {
            return base.Channel.LoginJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WiFiAAA.Open.LoginJsonResponse> LoginJsonAsync(string UserID, string UserPW, string UserIP, string OpenAPIVersion, string Token) {
            WiFiAAA.Open.LoginJsonRequest inValue = new WiFiAAA.Open.LoginJsonRequest();
            inValue.Body = new WiFiAAA.Open.LoginJsonRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.UserPW = UserPW;
            inValue.Body.UserIP = UserIP;
            inValue.Body.OpenAPIVersion = OpenAPIVersion;
            inValue.Body.Token = Token;
            return ((WiFiAAA.Open.OpenAAASoap)(this)).LoginJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WiFiAAA.Open.KeepSessionResponse WiFiAAA.Open.OpenAAASoap.KeepSession(WiFiAAA.Open.KeepSessionRequest request) {
            return base.Channel.KeepSession(request);
        }
        
        public string KeepSession(string UserID, string Token) {
            WiFiAAA.Open.KeepSessionRequest inValue = new WiFiAAA.Open.KeepSessionRequest();
            inValue.Body = new WiFiAAA.Open.KeepSessionRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.Token = Token;
            WiFiAAA.Open.KeepSessionResponse retVal = ((WiFiAAA.Open.OpenAAASoap)(this)).KeepSession(inValue);
            return retVal.Body.KeepSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WiFiAAA.Open.KeepSessionResponse> WiFiAAA.Open.OpenAAASoap.KeepSessionAsync(WiFiAAA.Open.KeepSessionRequest request) {
            return base.Channel.KeepSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WiFiAAA.Open.KeepSessionResponse> KeepSessionAsync(string UserID, string Token) {
            WiFiAAA.Open.KeepSessionRequest inValue = new WiFiAAA.Open.KeepSessionRequest();
            inValue.Body = new WiFiAAA.Open.KeepSessionRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.Token = Token;
            return ((WiFiAAA.Open.OpenAAASoap)(this)).KeepSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WiFiAAA.Open.LogoutResponse WiFiAAA.Open.OpenAAASoap.Logout(WiFiAAA.Open.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public string Logout(string UserID, string Token) {
            WiFiAAA.Open.LogoutRequest inValue = new WiFiAAA.Open.LogoutRequest();
            inValue.Body = new WiFiAAA.Open.LogoutRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.Token = Token;
            WiFiAAA.Open.LogoutResponse retVal = ((WiFiAAA.Open.OpenAAASoap)(this)).Logout(inValue);
            return retVal.Body.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WiFiAAA.Open.LogoutResponse> WiFiAAA.Open.OpenAAASoap.LogoutAsync(WiFiAAA.Open.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WiFiAAA.Open.LogoutResponse> LogoutAsync(string UserID, string Token) {
            WiFiAAA.Open.LogoutRequest inValue = new WiFiAAA.Open.LogoutRequest();
            inValue.Body = new WiFiAAA.Open.LogoutRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.Token = Token;
            return ((WiFiAAA.Open.OpenAAASoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WiFiAAA.Open.GetTokenPictureBytesResponse WiFiAAA.Open.OpenAAASoap.GetTokenPictureBytes(WiFiAAA.Open.GetTokenPictureBytesRequest request) {
            return base.Channel.GetTokenPictureBytes(request);
        }
        
        public byte[] GetTokenPictureBytes() {
            WiFiAAA.Open.GetTokenPictureBytesRequest inValue = new WiFiAAA.Open.GetTokenPictureBytesRequest();
            inValue.Body = new WiFiAAA.Open.GetTokenPictureBytesRequestBody();
            WiFiAAA.Open.GetTokenPictureBytesResponse retVal = ((WiFiAAA.Open.OpenAAASoap)(this)).GetTokenPictureBytes(inValue);
            return retVal.Body.GetTokenPictureBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WiFiAAA.Open.GetTokenPictureBytesResponse> WiFiAAA.Open.OpenAAASoap.GetTokenPictureBytesAsync(WiFiAAA.Open.GetTokenPictureBytesRequest request) {
            return base.Channel.GetTokenPictureBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WiFiAAA.Open.GetTokenPictureBytesResponse> GetTokenPictureBytesAsync() {
            WiFiAAA.Open.GetTokenPictureBytesRequest inValue = new WiFiAAA.Open.GetTokenPictureBytesRequest();
            inValue.Body = new WiFiAAA.Open.GetTokenPictureBytesRequestBody();
            return ((WiFiAAA.Open.OpenAAASoap)(this)).GetTokenPictureBytesAsync(inValue);
        }
    }
}
